name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  actions: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact (webapp) from latest successful build on main
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: webapp
          path: dist

      - name: Create zip of build artifact
        run: |
          cd dist
          zip -r ../webapp.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "USTP CI/CD Tetris ${{ github.ref_name }}"
          generate_release_notes: true
          files: webapp.zip
